[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "keyfile.toml"

[android_device_oneplus_dodge]
source = "github"
github = "LineageOS/android_device_oneplus_dodge"

[android_device_oneplus_sm8750-common]
source = "github"
github = "LineageOS/android_device_oneplus_sm8750-common"

[android_hardware_oplus]
source = "github"
github = "LineageOS/android_hardware_oplus"

[android_kernel_oneplus_sm8750]
source = "github"
github = "LineageOS/android_kernel_oneplus_sm8750"

[android_kernel_oneplus_sm8750-devicetrees]
source = "github"
github = "LineageOS/android_kernel_oneplus_sm8750-devicetrees"

[android_kernel_oneplus_sm8750-modules]
source = "github"
github = "LineageOS/android_kernel_oneplus_sm8750-modules"
